spring:
  application:
    name: showtime-service
  profiles:
    active: dev
server:
  servlet:
    context-path: /taller2/api/v1
  port: 9070
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/
feign:
  circuitbreaker:
    enabled: true

