spring:
  application:
    name: user-service
  profiles:
    active: dev
server:
  servlet:
    context-path: /taller2/api/v1
  port: 9050
eureka:
  client:
     registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9010/eureka/
feign:
  circuitbreaker:
    enabled: true